version: "2"

services:
  web:
    build: .
    container_name: simple
    ports:
      - "8080:8080"
    links:
      - selenium
  selenium:
    image: selenium/standalone-firefox
    shm_size: 2g
    ports:
      - "4444:4444"
