web:
  build: .
  container_name: simple
  dockerfile: Dockerfile
  ports:
    - "8080:8080"
  links:
    - selenium
selenium:
  image: selenium/standalone-firefox
  shm_size: 2g
  ports:
    - "4444:4444"
